server:
  port: 8081
spring:
  shardingsphere:
    datasource:
      names: sharding0,sharding1
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.234.137:3306/testdb01
        username: root
        password: 123456
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.234.138:3306/testdb02
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          kpi_info:
            actual-data-nodes: db$->{0..1}.kpi_info_$->{0..1}
            database-strategy:
              standard:
                sharding-column: task_id
                sharding-algorithm-name: db_hash_mod
            table-strategy:
              standard:
                sharding-column: ne_id
                sharding-algorithm-name: db_hash_mod
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        key-generators:
          snowflake:
            type: SNOWFLAKE


        sharding-algorithms:
          db_hash_mod:
            type: HASH_MOD
            props:
              sharding-count: 2
          kpi_tab_alg:
            type: INLINE
            props:
              algorithm-expression: kpi_info_${ne_id}_${mu_id}_${mc_id}_${period}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lk.sharding_sphere.entity
  configuration:
    map-underscore-to-camel-case: true
